--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
-- Dumped by pg_dump version 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_archive; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_archive (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title text NOT NULL,
    author_id bigint NOT NULL
);


ALTER TABLE public.common_archive OWNER TO postgres;

--
-- Name: common_archive_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_archive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_archive_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_banneduser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_banneduser (
    id bigint NOT NULL,
    reason text NOT NULL,
    banned_until timestamp with time zone NOT NULL,
    banned_at timestamp with time zone NOT NULL,
    telegram_profile_id bigint NOT NULL
);


ALTER TABLE public.common_banneduser OWNER TO postgres;

--
-- Name: common_banneduser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_banneduser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_banneduser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_code (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.common_code OWNER TO postgres;

--
-- Name: common_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_language; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_language (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(31) NOT NULL,
    code character varying(31) NOT NULL
);


ALTER TABLE public.common_language OWNER TO postgres;

--
-- Name: common_language_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_language ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_language_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_requiredchannels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_requiredchannels (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(255) NOT NULL,
    url character varying(511) NOT NULL,
    username character varying(255),
    chat_id character varying(255)
);


ALTER TABLE public.common_requiredchannels OWNER TO postgres;

--
-- Name: common_requiredchannels_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_requiredchannels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_requiredchannels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_telegramprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_telegramprofile (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    chat_id character varying(31) NOT NULL,
    username character varying(255),
    first_name character varying(255) NOT NULL,
    last_name character varying(255),
    role character varying(255) NOT NULL,
    language character varying(7)
);


ALTER TABLE public.common_telegramprofile OWNER TO postgres;

--
-- Name: common_telegramprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_telegramprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_telegramprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: common_text; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.common_text (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    value text NOT NULL,
    type character varying(31) NOT NULL,
    "order" smallint NOT NULL,
    code_id bigint NOT NULL,
    language_id bigint NOT NULL,
    CONSTRAINT common_text_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.common_text OWNER TO postgres;

--
-- Name: common_text_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.common_text ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.common_text_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add crontab	7	add_crontabschedule
26	Can change crontab	7	change_crontabschedule
27	Can delete crontab	7	delete_crontabschedule
28	Can view crontab	7	view_crontabschedule
29	Can add interval	8	add_intervalschedule
30	Can change interval	8	change_intervalschedule
31	Can delete interval	8	delete_intervalschedule
32	Can view interval	8	view_intervalschedule
33	Can add periodic task	9	add_periodictask
34	Can change periodic task	9	change_periodictask
35	Can delete periodic task	9	delete_periodictask
36	Can view periodic task	9	view_periodictask
37	Can add periodic task track	10	add_periodictasks
38	Can change periodic task track	10	change_periodictasks
39	Can delete periodic task track	10	delete_periodictasks
40	Can view periodic task track	10	view_periodictasks
41	Can add solar event	11	add_solarschedule
42	Can change solar event	11	change_solarschedule
43	Can delete solar event	11	delete_solarschedule
44	Can view solar event	11	view_solarschedule
45	Can add clocked	12	add_clockedschedule
46	Can change clocked	12	change_clockedschedule
47	Can delete clocked	12	delete_clockedschedule
48	Can view clocked	12	view_clockedschedule
49	Can add code	13	add_code
50	Can change code	13	change_code
51	Can delete code	13	delete_code
52	Can view code	13	view_code
53	Can add language	14	add_language
54	Can change language	14	change_language
55	Can delete language	14	delete_language
56	Can view language	14	view_language
57	Can add required channels	15	add_requiredchannels
58	Can change required channels	15	change_requiredchannels
59	Can delete required channels	15	delete_requiredchannels
60	Can view required channels	15	view_requiredchannels
61	Can add telegram profile	16	add_telegramprofile
62	Can change telegram profile	16	change_telegramprofile
63	Can delete telegram profile	16	delete_telegramprofile
64	Can view telegram profile	16	view_telegramprofile
65	Can add banned user	17	add_banneduser
66	Can change banned user	17	change_banneduser
67	Can delete banned user	17	delete_banneduser
68	Can view banned user	17	view_banneduser
69	Can add archive	18	add_archive
70	Can change archive	18	change_archive
71	Can delete archive	18	delete_archive
72	Can view archive	18	view_archive
73	Can add text	19	add_text
74	Can change text	19	change_text
75	Can delete text	19	delete_text
76	Can view text	19	view_text
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$720000$nOlsgW6Mipru3FIAxiEs8f$ydn3PjuUMchs5gw1wZ4sWyvxZkwA6k7bcc+4NpvvZVI=	2024-12-08 00:17:06.046598+05	t	fireplay				t	t	2024-12-08 00:16:48.212972+05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: common_archive; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_archive (id, created_at, updated_at, title, author_id) FROM stdin;
\.


--
-- Data for Name: common_banneduser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_banneduser (id, reason, banned_until, banned_at, telegram_profile_id) FROM stdin;
\.


--
-- Data for Name: common_code; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_code (id, created_at, updated_at, title) FROM stdin;
\.


--
-- Data for Name: common_language; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_language (id, created_at, updated_at, title, code) FROM stdin;
\.


--
-- Data for Name: common_requiredchannels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_requiredchannels (id, created_at, updated_at, title, url, username, chat_id) FROM stdin;
1	2024-12-10 20:44:45.747206+05	2024-12-11 00:33:21.381916+05	my projects	https://t.me/my_py_projects	my_py_projects	-1002116075549
2	2024-12-12 08:55:51.721807+05	2024-12-12 08:55:51.721822+05	Telegram bot	https://t.me/+xFOqlL0PEj40Y2Nh	+xFOqlL0PEj40Y2Nh	-1001803581275
\.


--
-- Data for Name: common_telegramprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_telegramprofile (id, created_at, updated_at, chat_id, username, first_name, last_name, role, language) FROM stdin;
2	2024-12-08 00:20:01.479738+05	2024-12-08 00:20:01.47975+05	1041026310	egamberdiqulov	Largo	\N	user	\N
4	2024-12-08 00:20:01.481678+05	2024-12-08 00:20:01.481687+05	439572222	RoziyaAmriddinovna	Roziya Amriddinovna	\N	user	\N
5	2024-12-08 00:20:01.482533+05	2024-12-08 00:20:01.482542+05	1270725142	nodirbec23	N O D I R B E K 🌏	\N	user	\N
6	2024-12-08 00:20:01.483411+05	2024-12-08 00:20:01.483419+05	1127226531	Muallimaat_school	Nafisa Nur	\N	user	\N
7	2024-12-08 00:20:01.484154+05	2024-12-08 00:20:01.484161+05	6757808098	\N	Go‘zal	\N	user	\N
8	2024-12-08 00:20:01.484888+05	2024-12-08 00:20:01.484895+05	6480409751	Umarjon_Avlayorov_TDTU	Avlayorov Umarjon	\N	user	\N
9	2024-12-08 00:20:01.485601+05	2024-12-08 00:20:01.485607+05	6397626261	Behruzbek_Azizov	𝙱𝚎𝚑𝚛𝚞𝚣𝚋𝚎𝚔🔰	\N	user	\N
10	2024-12-08 00:20:01.486321+05	2024-12-08 00:20:01.486326+05	1285913443	jummuserk	Jumayev Mustafo	\N	user	\N
11	2024-12-08 00:20:01.487306+05	2024-12-08 00:20:01.487312+05	1843632120	dr_Erali_Sherqobilovich	Dr_Erali_Sherqobilovich	\N	user	\N
12	2024-12-08 00:20:01.488301+05	2024-12-08 00:20:01.488308+05	2052913809	\N	nodirovna.m	\N	user	\N
13	2024-12-08 00:20:01.489373+05	2024-12-08 00:20:01.48938+05	152503390	\N	Jaxongir	\N	user	\N
14	2024-12-08 00:20:01.490375+05	2024-12-08 00:20:01.490382+05	5479637115	Web_Developer_Uzoqov	<Senior/>_Azizbek	\N	user	\N
15	2024-12-08 00:20:01.491016+05	2024-12-08 00:20:01.491021+05	1329790448	\N	ℳ𝒶𝓈𝒽𝓇𝒶𝒷𝓀𝒽ℴ𝓃 ❥︎	\N	user	\N
16	2024-12-08 00:20:01.491614+05	2024-12-08 00:20:01.491619+05	6505174629	shohjaxon_vv	Shohjaxon 	\N	user	\N
17	2024-12-08 00:20:01.492209+05	2024-12-08 00:20:01.492214+05	1228405859	Abduraxmonov_Javoxir	JAVOHIR	\N	user	\N
18	2024-12-08 00:20:01.49279+05	2024-12-08 00:20:01.492794+05	5878394227	the_no_mercy	X.H.Safarovich	\N	user	\N
19	2024-12-08 00:20:01.493365+05	2024-12-08 00:20:01.493369+05	1806867239	Kazakova_Malika	مليكة كازاكوفا	\N	user	\N
20	2024-12-08 00:20:01.493947+05	2024-12-08 00:20:01.493951+05	5742389892	kam1lovic	Мухаммад	\N	user	\N
21	2024-12-08 00:20:01.494522+05	2024-12-08 00:20:01.494527+05	5312260362	IT_Programmer_05	『ɪᴛ』 Ꮮ 𝚘 𝚛 𝚎 𝚗 ᴢ 𝚘 ×͜× ⁹⁹⁹	\N	user	\N
22	2024-12-08 00:20:01.495183+05	2024-12-08 00:20:01.495189+05	1254466520	\N	khasanmamatov1	\N	user	\N
23	2024-12-08 00:20:01.495875+05	2024-12-08 00:20:01.49588+05	875294125	admiral_on	ℋ𝒶𝓂𝒾𝒹𝒿ℴ𝓃 𝒯ℴ𝓈𝒽𝓅ℴ'𝓁ℴ𝓉ℴ𝓋	\N	user	\N
24	2024-12-08 00:20:01.49644+05	2024-12-08 00:20:01.496444+05	5649321700	SunnatPyDev	Sunnat_PyDev	\N	user	\N
25	2024-12-08 00:20:01.497014+05	2024-12-08 00:20:01.497018+05	5266641307	Sherzod_Elite	Sherzod	\N	user	\N
26	2024-12-08 00:20:01.497572+05	2024-12-08 00:20:01.497576+05	5126374949	United_gm	A	\N	user	\N
27	2024-12-08 00:20:01.498427+05	2024-12-08 00:20:01.498432+05	7164888977	look_for08	Atomic Habits	\N	user	\N
28	2024-12-08 00:20:01.499295+05	2024-12-08 00:20:01.4993+05	1206181129	La_1tahzan	𒊹︎︎︎ 𝐀𝐯𝐚𝐳𝐛𝐞𝐤 𝐏𝐫𝐢𝐦𝐪𝐮𝐥𝐨𝐯 𒊹︎︎︎	\N	user	\N
29	2024-12-08 00:20:01.500112+05	2024-12-08 00:20:01.500116+05	6686514726	pdpsales06	PDP |	\N	user	\N
30	2024-12-08 00:20:01.500975+05	2024-12-08 00:20:01.500988+05	2032947870	QodirovaLatofat81	لاتوفات.	\N	user	\N
31	2024-12-08 00:20:01.501529+05	2024-12-08 00:20:01.501533+05	816364711	\N	Imomova Fotima	\N	user	\N
32	2024-12-08 00:20:01.502064+05	2024-12-08 00:20:01.502067+05	655269502	Ugusha94	Испандиярова Углой	\N	user	\N
33	2024-12-08 00:20:01.502607+05	2024-12-08 00:20:01.502611+05	849647941	dilshod_uskanov	Dilshod Uskanov	\N	user	\N
34	2024-12-08 00:20:01.503156+05	2024-12-08 00:20:01.50316+05	2124744962	Jamshid_01072003	Jamshid	\N	user	\N
35	2024-12-08 00:20:01.503708+05	2024-12-08 00:20:01.503712+05	1136306403	makhzun	Python	\N	user	\N
36	2024-12-08 00:20:01.504282+05	2024-12-08 00:20:01.504286+05	2042927717	JaxangirAytjanov	Jaxangir Aytjanov	\N	user	\N
37	2024-12-08 00:20:01.504872+05	2024-12-08 00:20:01.504876+05	735515716	\N	Bozorbek Omonov	\N	user	\N
38	2024-12-08 00:20:01.505442+05	2024-12-08 00:20:01.505446+05	6138288115	yarki_o	Yorqinjon	\N	user	\N
39	2024-12-08 00:20:01.506035+05	2024-12-08 00:20:01.506039+05	6681208527	\N	Umirov	\N	user	\N
40	2024-12-08 00:20:01.506618+05	2024-12-08 00:20:01.506622+05	6053508960	Uzbrmkm	🧑‍💻Shaxzod	\N	user	\N
41	2024-12-08 00:20:01.507341+05	2024-12-08 00:20:01.507349+05	260330043	Abdullo_20_05	Умида Мамадалиева Мойиджоновна	\N	user	\N
42	2024-12-08 00:20:01.508157+05	2024-12-08 00:20:01.508165+05	6509596664	\N	Olimov	\N	user	\N
43	2024-12-08 00:20:01.509202+05	2024-12-08 00:20:01.509208+05	6935308294	\N	Muhammadyusuf	\N	user	\N
44	2024-12-08 00:20:01.510155+05	2024-12-08 00:20:01.51016+05	1900845860	Software_developer_01	Asliddinkhan	\N	user	\N
45	2024-12-08 00:20:01.51109+05	2024-12-08 00:20:01.511095+05	937258544	\N	Durdona	\N	user	\N
46	2024-12-08 00:20:01.511946+05	2024-12-08 00:20:01.51195+05	1177182276	Developer_JB	Mr.Yusufbek	\N	user	\N
47	2024-12-08 00:20:01.512633+05	2024-12-08 00:20:01.512638+05	1258550420	Kholmakhmatov_A	ᴷʰᵒˡᵐᵃᵏʰᵐᵃᵗᵒᵛ_ᴬ	\N	user	\N
48	2024-12-08 00:20:01.513224+05	2024-12-08 00:20:01.513229+05	1612891723	khaydarov_senior	khaydarov	\N	user	\N
49	2024-12-08 00:20:01.51379+05	2024-12-08 00:20:01.513794+05	1924444167	\N	ADM1N	\N	user	\N
50	2024-12-08 00:20:01.514398+05	2024-12-08 00:20:01.514404+05	1330696129	behzodfarkhodov	FARKHODOFF	\N	user	\N
51	2024-12-08 00:20:01.515076+05	2024-12-08 00:20:01.515081+05	5343133375	\N	Рустам	\N	user	\N
52	2024-12-08 00:20:01.515761+05	2024-12-08 00:20:01.515766+05	2041478247	Maqsadlar_bajariladi	• ʀᴀsᴜʟᴏᴠ ᴏɢʻᴀʙᴇᴋ ོོ	\N	user	\N
53	2024-12-08 00:20:01.516449+05	2024-12-08 00:20:01.516455+05	6091376872	Zava_3	.	\N	user	\N
54	2024-12-08 00:20:01.5172+05	2024-12-08 00:20:01.517205+05	6977869750	Iroda_o5o9	Ирода Ахмадова👩‍💻	\N	user	\N
55	2024-12-08 00:20:01.517896+05	2024-12-08 00:20:01.517902+05	5936163415	FrontEndDasturchi2024	🔒 ➕ 🔑 = 🔓	\N	user	\N
56	2024-12-08 00:20:01.518604+05	2024-12-08 00:20:01.518609+05	428269520	Absamatov_Sohibjon	Sohibjon	\N	user	\N
57	2024-12-08 00:20:01.519281+05	2024-12-08 00:20:01.519287+05	5783504087	sabirovn_a	.	\N	user	\N
58	2024-12-08 00:20:01.519875+05	2024-12-08 00:20:01.51988+05	5205217663	nili_mee1	Нилуфар Сапарбаева	\N	user	\N
59	2024-12-08 00:20:01.52083+05	2024-12-08 00:20:01.520836+05	2014342206	Jalolforuq	𝙼𝚛.𝙸𝚗𝚌𝚘𝚐𝚗𝚒𝚝𝚘	\N	user	\N
60	2024-12-08 00:20:01.521829+05	2024-12-08 00:20:01.521835+05	666069819	Mirzayev_0262	uLuG'bEk	\N	user	\N
61	2024-12-08 00:20:01.5228+05	2024-12-08 00:20:01.522806+05	228954473	bahti_asakinskiy	Бахтиёр Исакжанов™	\N	user	\N
62	2024-12-08 00:20:01.523773+05	2024-12-08 00:20:01.523778+05	451198587	\N	Б.Х	\N	user	\N
63	2024-12-08 00:20:01.524357+05	2024-12-08 00:20:01.524362+05	700896686	uzbbdev	Ibadulla	\N	user	\N
64	2024-12-08 00:20:01.524929+05	2024-12-08 00:20:01.524932+05	5652736081	MirmaxsudovAbdurahmon	Abdurahmon	\N	user	\N
65	2024-12-08 00:20:01.525545+05	2024-12-08 00:20:01.525548+05	5818032954	Musulman_boy	﷽꯭❴꯭🌙꯭❵꯭◌꯭❥꯭◦꯭⋅ 𝚈𝙾𝚀𝚄𝙱𝙹𝙾𝙽 🕋꯭꯭ཻ࿆◌꯭❥꯭◦⋅꯭❴꯭📿꯭❵꯭ﷺ	\N	user	\N
66	2024-12-08 00:20:01.526077+05	2024-12-08 00:20:01.52608+05	1004329317	Baxtiyarova7	Baxtiyarova Xurshida	\N	user	\N
67	2024-12-08 00:20:01.526599+05	2024-12-08 00:20:01.526602+05	6879460747	Frontend_programmer_oo7	<khayrullayevaDev/>	\N	user	\N
68	2024-12-08 00:20:01.527129+05	2024-12-08 00:20:01.527133+05	5343557348	berdiyevoybek	Oybek	\N	user	\N
69	2024-12-08 00:20:01.527931+05	2024-12-08 00:20:01.527941+05	6063023666	\N	Gulnoza Jo'raboyeva	\N	user	\N
70	2024-12-08 00:20:01.52867+05	2024-12-08 00:20:01.528676+05	5076306432	love_is_King	🤴Sevgi_Qiroli🤴	\N	user	\N
71	2024-12-08 00:20:01.529364+05	2024-12-08 00:20:01.529369+05	6583791224	matyoqubov_08	☬ 𝙼𝚊𝚝𝚢𝚘𝚚𝚞𝚋𝚘𝚟	\N	user	\N
72	2024-12-08 00:20:01.530101+05	2024-12-08 00:20:01.530106+05	5792169652	barkamol_o4	Nazirqulov Barkamol	\N	user	\N
3	2024-12-08 00:20:01.480759+05	2024-12-10 21:05:57.70835+05	2026251138	\N	Microsoft	\N	admin	\N
73	2024-12-08 00:20:01.530841+05	2024-12-08 00:20:01.530847+05	706264819	Behruzbek_Gafurov	Behruzbey_Gafurov	\N	user	\N
74	2024-12-08 00:20:01.531544+05	2024-12-08 00:20:01.531549+05	7074108652	\N	Xalilova Maftuna	\N	user	\N
75	2024-12-08 00:20:01.532632+05	2024-12-08 00:20:01.532639+05	6398876678	\N	Улуғбек	\N	user	\N
76	2024-12-08 00:20:01.533557+05	2024-12-08 00:20:01.533562+05	600188492	Muhammaddiyor_Abdumalikov	Muhammaddiyor	\N	user	\N
77	2024-12-08 00:20:01.534517+05	2024-12-08 00:20:01.534522+05	6063622968	\N	Sevinch	\N	user	\N
78	2024-12-08 00:20:01.535467+05	2024-12-08 00:20:01.535472+05	1320640154	khnosirov	Khabibullo	\N	user	\N
79	2024-12-08 00:20:01.536111+05	2024-12-08 00:20:01.536116+05	1007024996	\N	Nasiba Abdullayeva	\N	user	\N
80	2024-12-08 00:20:01.536699+05	2024-12-08 00:20:01.536703+05	843972471	Akmalyuldash	Akmal	\N	user	\N
81	2024-12-08 00:20:01.53737+05	2024-12-08 00:20:01.537375+05	6351832516	\N	Гулшода Махмудова	\N	user	\N
82	2024-12-08 00:20:01.538081+05	2024-12-08 00:20:01.538086+05	6415420240	\N	د	\N	user	\N
83	2024-12-08 00:20:01.53865+05	2024-12-08 00:20:01.538654+05	1459109370	rakhmetullakabilov	Рахметулла	\N	user	\N
84	2024-12-08 00:20:01.539311+05	2024-12-08 00:20:01.539316+05	6977939907	SReldSales	SR ELD Sales	\N	user	\N
85	2024-12-08 00:20:01.539898+05	2024-12-08 00:20:01.539902+05	5692267415	angrenmega	МЕГАЦЕНТР	\N	user	\N
86	2024-12-08 00:20:01.540646+05	2024-12-08 00:20:01.540651+05	43511328	FazliddinJamilov	Жамилов	\N	user	\N
87	2024-12-08 00:20:01.541345+05	2024-12-08 00:20:01.541351+05	6146446977	T6rabek	To'rabek ᯤ̸	\N	user	\N
88	2024-12-08 00:20:01.541981+05	2024-12-08 00:20:01.541988+05	5176095828	asilbek_rustamov	Асилбек Рустамов	\N	user	\N
89	2024-12-08 00:20:01.542713+05	2024-12-08 00:20:01.542718+05	527554493	Samandar09998	Alimbetova Guljamal Joldasbaevna	\N	user	\N
90	2024-12-08 00:20:01.543391+05	2024-12-08 00:20:01.543395+05	1313922637	\N	Farangiz	\N	user	\N
91	2024-12-08 00:20:01.546704+05	2024-12-08 00:20:01.546713+05	6272336605	nozima_0441	Nozima	\N	user	\N
92	2024-12-08 00:20:01.547808+05	2024-12-08 00:20:01.547822+05	6340176349	aikarimovvv	Abdurahim	\N	user	\N
93	2024-12-08 00:20:01.549+05	2024-12-08 00:20:01.54901+05	1774867377	Obloqulova_Rayhonabonu	Rayhonabonu Obloqulova	\N	user	\N
94	2024-12-08 00:20:01.550389+05	2024-12-08 00:20:01.550395+05	6175838162	abdurajabovogabek	Abdurajabov	\N	user	\N
95	2024-12-08 00:20:01.551301+05	2024-12-08 00:20:01.551306+05	2041360701	mominov_a	Арслон	\N	user	\N
96	2024-12-08 00:20:01.551919+05	2024-12-08 00:20:01.551923+05	722163836	\N	АБДУСАТТОР	\N	user	\N
97	2024-12-08 00:20:01.552633+05	2024-12-08 00:20:01.552638+05	2126157087	FFS84	А.Шарапова	\N	user	\N
98	2024-12-08 00:20:01.553325+05	2024-12-08 00:20:01.553331+05	6580101022	s_shirina	Ширин Салохиддинова	\N	user	\N
99	2024-12-08 00:20:01.553907+05	2024-12-08 00:20:01.553912+05	590811633	Mardon_judo_81	Mardon	\N	user	\N
100	2024-12-08 00:20:01.554586+05	2024-12-08 00:20:01.554591+05	6875786436	asilbek95kr	Asilbek	\N	user	\N
101	2024-12-08 00:20:01.555252+05	2024-12-08 00:20:01.555257+05	7120724207	SoqqaTrade	Trade	\N	user	\N
102	2024-12-08 00:20:01.555835+05	2024-12-08 00:20:01.555839+05	1605485221	Ya_habiybiy	سَروَرٌ	\N	user	\N
103	2024-12-08 00:20:01.556521+05	2024-12-08 00:20:01.556527+05	5781696760	Davranova_Nafisa_Abdihakimovna	Nafisa	\N	user	\N
104	2024-12-08 00:20:01.557145+05	2024-12-08 00:20:01.557151+05	2138806597	\N	Aliboyeva	\N	user	\N
105	2024-12-08 00:20:01.557852+05	2024-12-08 00:20:01.557857+05	384677084	\N	...	\N	user	\N
106	2024-12-08 00:20:01.558569+05	2024-12-08 00:20:01.558574+05	5873013330	AzizaKudaybergenova	Азиза	\N	user	\N
107	2024-12-08 00:20:01.559619+05	2024-12-08 00:20:01.559624+05	5007384925	\N	Ахмат	\N	user	\N
108	2024-12-08 00:20:01.560614+05	2024-12-08 00:20:01.560619+05	841560541	Shomurodov_Q_B	Qadamjon	\N	user	\N
109	2024-12-08 00:20:01.561596+05	2024-12-08 00:20:01.561602+05	752267478	Shuhrat1218	Shuhrat	\N	user	\N
110	2024-12-08 00:20:01.562612+05	2024-12-08 00:20:01.562618+05	5262304265	qironov	husniddin.qiranov	\N	user	\N
111	2024-12-08 00:20:01.563331+05	2024-12-08 00:20:01.563337+05	5206434640	islombek_w	Islombek	\N	user	\N
112	2024-12-08 00:20:01.563916+05	2024-12-08 00:20:01.563921+05	5800562598	\N	С	\N	user	\N
113	2024-12-08 00:20:01.564608+05	2024-12-08 00:20:01.564614+05	1857139314	Tohirjon_Bakhtiyarovich	Toxirjon Mirzaqulov	\N	user	\N
114	2024-12-08 00:20:01.565253+05	2024-12-08 00:20:01.565258+05	860973504	UUNLOCKEDD	ГУЛАЙЫМ	\N	user	\N
115	2024-12-08 00:20:01.565835+05	2024-12-08 00:20:01.565839+05	2092352825	\N	Patience	\N	user	\N
116	2024-12-08 00:20:01.566379+05	2024-12-08 00:20:01.566383+05	6741619592	xusniddinovna_aziza	Aziza	\N	user	\N
117	2024-12-08 00:20:01.566914+05	2024-12-08 00:20:01.566917+05	522932158	Mekxrojjon	Mekxrojjon	\N	user	\N
118	2024-12-08 00:20:01.56754+05	2024-12-08 00:20:01.567544+05	6563120175	IELTS_Instructor_D	🏳	\N	user	\N
119	2024-12-08 00:20:01.568268+05	2024-12-08 00:20:01.568278+05	5146085066	G_Abdurasulov	//Gʻolibjon Abdurasulov	\N	user	\N
120	2024-12-08 00:20:01.569101+05	2024-12-08 00:20:01.56912+05	567101590	arzigul_kenesbaeva8	Arzigúl	\N	user	\N
121	2024-12-08 00:20:01.570085+05	2024-12-08 00:20:01.570091+05	6441319389	Sesalll	Kengesbaeva Tamara	\N	user	\N
122	2024-12-08 00:20:01.570706+05	2024-12-08 00:20:01.57071+05	5235561360	qmkdm	мк	\N	user	\N
123	2024-12-08 00:20:01.571707+05	2024-12-08 00:20:01.571712+05	6069934462	Kom_qizmetler	👨🏻‍💻🫀	\N	user	\N
124	2024-12-08 00:20:01.572598+05	2024-12-08 00:20:01.572602+05	313859997	orange0706	Dilshodbek	\N	user	\N
125	2024-12-08 00:20:01.573442+05	2024-12-08 00:20:01.573446+05	1875345938	\N	.	\N	user	\N
126	2024-12-08 00:20:01.57445+05	2024-12-08 00:20:01.574457+05	648880757	D_Kurbiyazov	Dilshodbek	\N	user	\N
127	2024-12-08 00:20:01.575128+05	2024-12-08 00:20:01.575133+05	5336229946	R4700	Асадбек	\N	user	\N
128	2024-12-08 00:20:01.575711+05	2024-12-08 00:20:01.575716+05	7047672447	Mirazim1902	Mirazim	\N	user	\N
129	2024-12-08 00:20:01.576325+05	2024-12-08 00:20:01.576328+05	5051152190	\N	Simple boy	\N	user	\N
130	2024-12-08 00:20:01.576885+05	2024-12-08 00:20:01.576891+05	1252074086	Yulchiyeva_Nozima	Yulchiyeva	\N	user	\N
131	2024-12-08 00:20:01.577576+05	2024-12-08 00:20:01.577592+05	5251832260	Java_hp	Azamat	\N	user	\N
132	2024-12-08 00:20:01.578583+05	2024-12-08 00:20:01.578592+05	906143423	turganbaev_jorabek	Jorabek	\N	user	\N
133	2024-12-08 00:20:01.579465+05	2024-12-08 00:20:01.579472+05	765542361	asrorsolijonov	.	\N	user	\N
134	2024-12-08 00:20:01.580137+05	2024-12-08 00:20:01.580142+05	6828038288	\N	Жуманов	\N	user	\N
135	2024-12-08 00:20:01.58074+05	2024-12-08 00:20:01.580744+05	583649737	sagidat_kanatbayev	Sagidat	\N	user	\N
136	2024-12-08 00:20:01.581342+05	2024-12-08 00:20:01.581346+05	219762195	x_nurbek	Хамраев Нурбек	\N	user	\N
137	2024-12-08 00:20:01.582138+05	2024-12-08 00:20:01.582144+05	523438389	mukhtor94	M	\N	user	\N
138	2024-12-08 00:20:01.582756+05	2024-12-08 00:20:01.58276+05	5866894937	dl7171	Dostonbek	\N	user	\N
139	2024-12-08 00:20:01.583609+05	2024-12-08 00:20:01.583612+05	1771675353	azik2002sh	20001016	\N	user	\N
140	2024-12-08 00:20:01.584424+05	2024-12-08 00:20:01.584428+05	606395775	aiidanaa_19	𝓐𝔂𝓭𝓪𝓷𝓪🤍	\N	user	\N
141	2024-12-08 00:20:01.585252+05	2024-12-08 00:20:01.585256+05	1920065129	Konkastudor1	Sadriddin Siddiqov	\N	user	\N
142	2024-12-08 00:20:01.586014+05	2024-12-08 00:20:01.586018+05	5698611724	Nihola_Xusanova	Nihola	\N	user	\N
143	2024-12-08 00:20:01.586533+05	2024-12-08 00:20:01.586536+05	5283629049	Saparov_Abduvali	🗿	\N	user	\N
144	2024-12-08 00:20:01.587052+05	2024-12-08 00:20:01.587055+05	1053768318	\N	LANS	\N	user	\N
145	2024-12-08 00:20:01.587588+05	2024-12-08 00:20:01.587592+05	5537410813	Diyorbek_Saminov	Diyorbek	\N	user	\N
146	2024-12-08 00:20:01.588228+05	2024-12-08 00:20:01.588234+05	5817983253	Med_Akhmed	Мед	\N	user	\N
147	2024-12-08 00:20:01.588929+05	2024-12-08 00:20:01.588933+05	6722273111	Bintuabdulmohsin	بنت عبد المحسن	\N	user	\N
148	2024-12-08 00:20:01.589532+05	2024-12-08 00:20:01.589536+05	903603601	\N	Бауыржан	\N	user	\N
149	2024-12-08 00:20:01.590085+05	2024-12-08 00:20:01.590089+05	118830561	VFiresoul	Javlonbek	\N	user	\N
150	2024-12-08 00:20:01.590703+05	2024-12-08 00:20:01.590707+05	6536234302	kamoliddinovna_19	Luna	\N	user	\N
151	2024-12-08 00:20:01.591244+05	2024-12-08 00:20:01.591247+05	7006129031	Zaripov_20	Zaripov	\N	user	\N
152	2024-12-08 00:20:01.591769+05	2024-12-08 00:20:01.591772+05	5466584946	Program_8989	Shox	\N	user	\N
153	2024-12-08 00:20:01.592326+05	2024-12-08 00:20:01.59233+05	354668188	Mehrojbek_dev	Mehrojbek	\N	user	\N
154	2024-12-08 00:20:01.592847+05	2024-12-08 00:20:01.592851+05	912723931	Nazarov22222	Nazarov	\N	user	\N
155	2024-12-08 00:20:01.593656+05	2024-12-08 00:20:01.59366+05	7151048235	\N	Husan	\N	user	\N
156	2024-12-08 00:20:01.594463+05	2024-12-08 00:20:01.594466+05	1474065279	mathical_04	⌐╦╦═─⎝⎝✧𝘼𝙨𝙞𝙡𝙗𝙚𝙠—͟͟͞͞𖣘	\N	user	\N
157	2024-12-08 00:20:01.595303+05	2024-12-08 00:20:01.595307+05	6452256652	\N	سيد	\N	user	\N
158	2024-12-08 00:20:01.596168+05	2024-12-08 00:20:01.596173+05	5411985024	Pdp2004	Raxmonberdi	\N	user	\N
159	2024-12-08 00:20:01.596848+05	2024-12-08 00:20:01.596853+05	6376579717	husanxoja_98	꧁ 𝓤𝓵𝓾𝓰'𝔁𝓸𝓷𝓸𝓿 𝓗𝓾𝓼𝓪𝓷𝔁𝓸'𝓳𝓪 ꧂	\N	user	\N
160	2024-12-08 00:20:01.597535+05	2024-12-08 00:20:01.59754+05	1591907169	\N	УМИДА	\N	user	\N
161	2024-12-08 00:20:01.598261+05	2024-12-08 00:20:01.598266+05	754472910	\N	Еркебай Бегимбаевич	\N	user	\N
162	2024-12-08 00:20:01.598842+05	2024-12-08 00:20:01.598846+05	5623008953	\N	DILNAZA	\N	user	\N
163	2024-12-08 00:20:01.599499+05	2024-12-08 00:20:01.599504+05	6540640618	Islom_Razoqov	Ислом Разоков	\N	user	\N
164	2024-12-08 00:20:01.600107+05	2024-12-08 00:20:01.600112+05	597930552	Makhmudov99	Maxmudov	\N	user	\N
165	2024-12-08 00:20:01.600697+05	2024-12-08 00:20:01.600701+05	5244028182	Gucci_3233	ོ	\N	user	\N
166	2024-12-08 00:20:01.601365+05	2024-12-08 00:20:01.60137+05	5631088976	RafuzMe	Zufar	\N	user	\N
167	2024-12-08 00:20:01.601951+05	2024-12-08 00:20:01.601955+05	5942753298	aziza_abduvaliyeva	Aziza	\N	user	\N
168	2024-12-08 00:20:01.602565+05	2024-12-08 00:20:01.60257+05	1849499007	\N	♡	\N	user	\N
169	2024-12-08 00:20:01.60328+05	2024-12-08 00:20:01.603295+05	6302363003	SevaraMirzoyeva0606	SEVARA MIRZOYEVA	\N	user	\N
170	2024-12-08 00:20:01.604037+05	2024-12-08 00:20:01.604042+05	5631202601	\N	Qdirbaeva	\N	user	\N
171	2024-12-08 00:20:01.604929+05	2024-12-08 00:20:01.604932+05	2113568643	ddz444	Alimardonov Quvonchbek	\N	user	\N
172	2024-12-08 00:20:01.60589+05	2024-12-08 00:20:01.605895+05	6906682771	\N	Мурад	\N	user	\N
173	2024-12-08 00:20:01.606774+05	2024-12-08 00:20:01.606778+05	6934748192	\N	уд🌷	\N	user	\N
174	2024-12-08 00:20:01.607674+05	2024-12-08 00:20:01.60768+05	1299976473	saidalo_shamsiyev	Saidalo Shamsiyev	\N	user	\N
175	2024-12-08 00:20:01.608475+05	2024-12-08 00:20:01.608484+05	7188147073	\N	√	\N	user	\N
176	2024-12-08 00:20:01.609398+05	2024-12-08 00:20:01.609407+05	6585248068	shahlo_2106	Shahlo Esonova	\N	user	\N
177	2024-12-08 00:20:01.610196+05	2024-12-08 00:20:01.610203+05	934825814	hnab7925	᭄ꦿ᭄ꦿB̤̈͜͡Ö̤͜͡B̤̈͜͡Ö̤͜͡N̤̈͜͡Ä̤͜͡Z̤̈͜͡Ä̤͜͡R᭄̤̈͜͡ꦿ᭄ꦿ	\N	user	\N
178	2024-12-08 00:20:01.610806+05	2024-12-08 00:20:01.610818+05	491574951	Umarovich_96	Умарович_1🇺🇿	\N	user	\N
179	2024-12-08 00:20:01.611398+05	2024-12-08 00:20:01.611402+05	7166997486	\N	N	\N	user	\N
180	2024-12-08 00:20:01.611957+05	2024-12-08 00:20:01.61196+05	1624172225	ez0_zsmy	ez0_zsmy	\N	user	\N
181	2024-12-08 00:20:01.612518+05	2024-12-08 00:20:01.612521+05	622280609	Kreative19	Shuhrat	\N	user	\N
182	2024-12-08 00:20:01.613082+05	2024-12-08 00:20:01.613086+05	839549464	jaloliddinovak	Komilá	\N	user	\N
183	2024-12-08 00:20:01.613622+05	2024-12-08 00:20:01.613625+05	5961383385	\N	JUMABOYEV	\N	user	\N
184	2024-12-08 00:20:01.614136+05	2024-12-08 00:20:01.61414+05	997111296	aseliya_alimbayeva	Aseliya	\N	user	\N
185	2024-12-08 00:20:01.614685+05	2024-12-08 00:20:01.614689+05	1435826068	\N	𝖿𝗓𝗑 ⁷¹²	\N	user	\N
186	2024-12-08 00:20:01.6153+05	2024-12-08 00:20:01.615309+05	622852304	\N	Yuldashev	\N	user	\N
187	2024-12-08 00:20:01.616234+05	2024-12-08 00:20:01.616239+05	1131922381	tolybekov	Azizbek Tolıbekov	\N	user	\N
188	2024-12-08 00:20:01.617123+05	2024-12-08 00:20:01.617128+05	7162720662	\N	Davronovna	\N	user	\N
189	2024-12-08 00:20:01.618052+05	2024-12-08 00:20:01.618057+05	1204242620	lAzamat	Azamat Z.	\N	user	\N
190	2024-12-08 00:20:01.618961+05	2024-12-08 00:20:01.618967+05	327429081	IrodaMiraliyevna	✨𝐼𝑟𝑜𝑑𝑎 𝑀𝑖𝑟𝑎𝑙𝑖𝑦𝑒𝑣𝑛𝑎✨	\N	user	\N
191	2024-12-08 00:20:01.619553+05	2024-12-08 00:20:01.619557+05	6282989425	\N	Mohira	\N	user	\N
192	2024-12-08 00:20:01.62009+05	2024-12-08 00:20:01.620094+05	7090668413	Sho_murodov	Shomurodov	\N	user	\N
193	2024-12-08 00:20:01.620701+05	2024-12-08 00:20:01.620705+05	1475117567	Dostonjon_Usmonov_5054	Dostonjon	\N	user	\N
194	2024-12-08 00:20:01.62134+05	2024-12-08 00:20:01.621346+05	1413182124	\N	Kayipnazarov Damir.	\N	user	\N
195	2024-12-08 00:20:01.621938+05	2024-12-08 00:20:01.621942+05	5976376745	abduraxmon_athlete	𝙰𝙱𝙳𝚄𝚁𝙰𝚇𝙼𝙾𝙽	\N	user	\N
196	2024-12-08 00:20:01.622521+05	2024-12-08 00:20:01.622525+05	443841757	\N	Х Х	\N	user	\N
197	2024-12-08 00:20:01.623154+05	2024-12-08 00:20:01.623159+05	6318205339	\N	☠️	\N	user	\N
198	2024-12-08 00:20:01.623747+05	2024-12-08 00:20:01.623751+05	7103145845	TheBoburbek	Boburbek Rustembayev Muzaffarovich	\N	user	\N
199	2024-12-08 00:20:01.624428+05	2024-12-08 00:20:01.624433+05	787806948	world_06x	Хадича	\N	user	\N
200	2024-12-08 00:20:01.625068+05	2024-12-08 00:20:01.625073+05	1199541429	sh210990	Sattorova	\N	user	\N
201	2024-12-08 00:20:01.625618+05	2024-12-08 00:20:01.625622+05	6476189346	\N	Doston	\N	user	\N
202	2024-12-08 00:20:01.626109+05	2024-12-08 00:20:01.626113+05	855350870	nodirhon_uz	N	\N	user	\N
203	2024-12-08 00:20:01.626939+05	2024-12-08 00:20:01.626942+05	1744039892	kholdarova_nodiraxon	🌊Kholdarova Nodiraxon✨	\N	user	\N
204	2024-12-08 00:20:01.627841+05	2024-12-08 00:20:01.627847+05	135298970	\N	Eldorbek	\N	user	\N
205	2024-12-08 00:20:01.628753+05	2024-12-08 00:20:01.628759+05	1529593541	\N	Navruz	\N	user	\N
206	2024-12-08 00:20:01.629738+05	2024-12-08 00:20:01.629746+05	1937370691	Moxinur2021	Moxinur	\N	user	\N
207	2024-12-08 00:20:01.630497+05	2024-12-08 00:20:01.630507+05	1599164707	\N	Тонгатаров Қодир Хусниддинович	\N	user	\N
208	2024-12-08 00:20:01.631146+05	2024-12-08 00:20:01.631152+05	120859864	\N	Shahnoza	\N	user	\N
209	2024-12-08 00:20:01.631809+05	2024-12-08 00:20:01.631821+05	509960824	islombekjp	Islombek.meツ	\N	user	\N
210	2024-12-08 00:20:01.632561+05	2024-12-08 00:20:01.632565+05	1437028761	U_Z_B_11	𝙉𝙖𝙫𝙧𝙪𝙯	\N	user	\N
211	2024-12-08 00:20:01.633145+05	2024-12-08 00:20:01.633149+05	7163260272	\N	Samandar	\N	user	\N
212	2024-12-08 00:20:01.633707+05	2024-12-08 00:20:01.63371+05	5539454008	\N	Тамара	\N	user	\N
213	2024-12-08 00:20:01.634257+05	2024-12-08 00:20:01.634261+05	1071354314	Islomjon_0422	Sotiboldiev🇺🇿	\N	user	\N
214	2024-12-08 00:20:01.634893+05	2024-12-08 00:20:01.634896+05	1153308369	SoftwareEngineer05	Asadilloh Temirov	\N	user	\N
215	2024-12-08 00:20:01.635551+05	2024-12-08 00:20:01.635556+05	1000871678	DILMURODYOLDOSHEV	Dilmurod	\N	user	\N
216	2024-12-08 00:20:01.636176+05	2024-12-08 00:20:01.636182+05	1870689122	jamshid_elmurodov	Jamshid	\N	user	\N
217	2024-12-08 00:20:01.636747+05	2024-12-08 00:20:01.636751+05	6512834779	\N	.	\N	user	\N
218	2024-12-08 00:20:01.637469+05	2024-12-08 00:20:01.637474+05	7465752322	medstone_usmle_admin	Admin	\N	user	\N
219	2024-12-08 00:20:01.638389+05	2024-12-08 00:20:01.638394+05	1350137173	\N	🌸DILBAR🌸	\N	user	\N
220	2024-12-08 00:20:01.639272+05	2024-12-08 00:20:01.639277+05	6690786424	\N	رع	\N	user	\N
221	2024-12-08 00:20:01.640135+05	2024-12-08 00:20:01.64014+05	6924092325	\N	Магрипа	\N	user	\N
222	2024-12-08 00:20:01.640974+05	2024-12-08 00:20:01.640978+05	2129178263	nurmuhammad_zzz	Nurmuhammad	\N	user	\N
223	2024-12-08 00:20:01.641613+05	2024-12-08 00:20:01.641618+05	1036349301	UmiD_101	𝖀𝖒𝖎𝕯 𝕭𝖆𝖝𝖙𝖎𝖞𝖔𝖗𝖛𝖎𝖈𝖍️️	\N	user	\N
224	2024-12-08 00:20:01.642245+05	2024-12-08 00:20:01.64225+05	6400059626	\N	С.	\N	user	\N
225	2024-12-08 00:20:01.642874+05	2024-12-08 00:20:01.642878+05	779200856	UmidaChoriyeva	Umida A'zam qizi	\N	user	\N
226	2024-12-08 00:20:01.643522+05	2024-12-08 00:20:01.643526+05	304568297	graykiller	crvk	\N	user	\N
227	2024-12-08 00:20:01.644116+05	2024-12-08 00:20:01.64412+05	5905308473	Sunnatillo124	👑💎Sunnatillo💎👑	\N	user	\N
228	2024-12-08 00:20:01.644663+05	2024-12-08 00:20:01.644667+05	1107473199	ulugbek_05_23	𝕌𝕝𝕦𝕘'𝕓𝕖𝕜𓅓	\N	user	\N
229	2024-12-08 00:20:01.645351+05	2024-12-08 00:20:01.645356+05	1957936457	Dilmurodov1ch03	Jumanazar	\N	user	\N
230	2024-12-08 00:20:01.645944+05	2024-12-08 00:20:01.645948+05	994789438	Daniyor01	Usenov Daniyor	\N	user	\N
231	2024-12-08 00:20:01.646478+05	2024-12-08 00:20:01.646482+05	2033153488	xudoshukur03	Xudoshukur	\N	user	\N
232	2024-12-08 00:20:01.646966+05	2024-12-08 00:20:01.64697+05	833359980	\N	АK	\N	user	\N
233	2024-12-08 00:20:01.647482+05	2024-12-08 00:20:01.647486+05	7807221437	Uzatom_2030	꯭|꯭•꯭AVLAYOROV	\N	user	\N
234	2024-12-08 00:20:01.648145+05	2024-12-08 00:20:01.64815+05	6371438719	rmbvr	Reyimbaeva	\N	user	\N
235	2024-12-08 00:20:01.649015+05	2024-12-08 00:20:01.649021+05	1789518308	Logicleft	.....	\N	user	\N
236	2024-12-08 00:20:01.650092+05	2024-12-08 00:20:01.650097+05	6390130062	\N	ن Ergasheva	\N	user	\N
237	2024-12-08 00:20:01.651107+05	2024-12-08 00:20:01.651112+05	5580761572	a_aliyass	Abdurasulova Aliya	\N	user	\N
238	2024-12-08 00:20:01.651952+05	2024-12-08 00:20:01.651957+05	5445181265	Maxammadbek	𝑴𝒂𝒙𝒂𝒎𝒎𝒂𝒅𝒃𝒆𝒌	\N	user	\N
240	2024-12-08 00:23:03.959342+05	2024-12-08 00:23:03.959361+05	5494655384	baxtiyorovy	Yorqinbek	\N	user	\N
241	2024-12-08 00:23:03.965501+05	2024-12-08 00:23:03.965519+05	6700334337	Azada1112	Azada	\N	user	\N
242	2024-12-08 00:23:03.96748+05	2024-12-08 00:23:03.967496+05	6160929954	\N	Д	\N	user	\N
243	2024-12-08 00:23:03.969192+05	2024-12-08 00:23:03.969208+05	990252104	lazzat_allaniyazova	Лаззат	\N	user	\N
244	2024-12-08 00:23:03.970973+05	2024-12-08 00:23:03.970989+05	6409352168	\N	Камола	\N	user	\N
245	2024-12-08 00:23:03.972727+05	2024-12-08 00:23:03.972743+05	5707031554	\N	마흘리여	\N	user	\N
246	2024-12-08 00:23:03.974228+05	2024-12-08 00:23:03.974244+05	7199380899	MasjiduI_Aqso	بلال| 🇵🇸❤️🇺🇿	\N	user	\N
247	2024-12-08 00:23:03.975656+05	2024-12-08 00:23:03.975672+05	1660298130	Munavvar_11	Munavvar	\N	user	\N
1	2024-12-08 00:20:01.476635+05	2024-12-08 00:24:09.477129+05	6956376313	mcJahongir	Jahongir Uralovich	\N	admin	\N
\.


--
-- Data for Name: common_text; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.common_text (id, created_at, updated_at, value, type, "order", code_id, language_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-12-08 00:24:09.478214+05	1	mcJahongir	2	[{"changed": {"fields": ["Role"]}}]	16	1
2	2024-12-08 00:34:00.40293+05	1	BannedUser object (1)	3		17	1
3	2024-12-08 00:37:27.861821+05	2	BannedUser object (2)	3		17	1
4	2024-12-08 00:49:08.152278+05	5	BannedUser object (5)	3		17	1
5	2024-12-10 20:44:45.748716+05	1	my projects	1	[{"added": {}}]	15	1
6	2024-12-10 21:05:57.709356+05	3	Microsoft	2	[{"changed": {"fields": ["Role"]}}]	16	1
7	2024-12-10 21:14:14.220186+05	1	my projects	2	[]	15	1
8	2024-12-11 00:33:21.384494+05	1	my projects	2	[{"changed": {"fields": ["Chat id"]}}]	15	1
9	2024-12-12 08:55:51.722999+05	2	Telegram bot	1	[{"added": {}}]	15	1
10	2024-12-12 10:24:30.583501+05	286	s	3		18	1
11	2024-12-12 10:24:30.584751+05	285	mana	3		18	1
12	2024-12-12 10:24:30.585819+05	284	endichi	3		18	1
13	2024-12-12 10:24:30.586804+05	283	sad	3		18	1
14	2024-12-12 10:24:30.587891+05	282	xaxa	3		18	1
15	2024-12-12 10:24:30.589018+05	281	ads	3		18	1
16	2024-12-12 10:24:30.590272+05	280	sda	3		18	1
17	2024-12-12 10:24:30.591319+05	279	xaxa	3		18	1
18	2024-12-12 10:24:30.592342+05	278	t	3		18	1
19	2024-12-12 10:24:30.593326+05	277	qo'ymadingku	3		18	1
20	2024-12-12 10:24:30.594338+05	276	t	3		18	1
21	2024-12-12 10:24:30.595668+05	275	g	3		18	1
22	2024-12-12 10:24:30.597373+05	274	Приверт	3		18	1
23	2024-12-12 10:24:30.598461+05	273	Приверт	3		18	1
24	2024-12-12 10:24:30.59947+05	272	Как дела	3		18	1
25	2024-12-12 10:24:30.600458+05	271	Salom	3		18	1
26	2024-12-12 10:24:30.601134+05	270	#rasm\n\noe\natl! all S	3		18	1
27	2024-12-12 10:24:30.602002+05	269	#rasm\n\nsecond bot\nbo	3		18	1
28	2024-12-12 10:24:30.60295+05	268	#rasm\n\n<\n\nSE second 	3		18	1
29	2024-12-12 10:24:30.603776+05	267	Nima:	3		18	1
30	2024-12-12 10:24:30.60472+05	266	What	3		18	1
31	2024-12-12 10:24:30.605763+05	265	🥉	3		18	1
32	2024-12-12 10:24:30.606857+05	264	Xaxa	3		18	1
33	2024-12-12 10:24:30.607888+05	263	Jf	3		18	1
34	2024-12-12 10:24:30.608844+05	262	a	3		18	1
35	2024-12-12 10:24:30.609811+05	261	h	3		18	1
36	2024-12-12 10:24:30.61077+05	260	q	3		18	1
37	2024-12-12 10:24:30.61172+05	259	h	3		18	1
38	2024-12-12 10:24:30.613199+05	258	q	3		18	1
39	2024-12-12 10:24:30.614429+05	257	g'aybulla	3		18	1
40	2024-12-12 10:24:30.615447+05	256	do'nqay	3		18	1
41	2024-12-12 10:24:30.61617+05	255	Hello word	3		18	1
42	2024-12-12 10:24:30.616964+05	254	#rasm\n\nSiz ban qilin	3		18	1
43	2024-12-12 10:24:30.61773+05	253	#rasm\n\nJamshid aka\nl	3		18	1
44	2024-12-12 10:24:30.618603+05	252	kkalkdjfasd	3		18	1
45	2024-12-12 10:24:30.619568+05	251	khasldkjf	3		18	1
46	2024-12-12 10:24:30.620556+05	250	dfgfhg	3		18	1
47	2024-12-12 10:24:30.621543+05	249	asdak	3		18	1
48	2024-12-12 10:24:30.622593+05	248	f	3		18	1
49	2024-12-12 10:24:30.623703+05	247	zaybal qimaye	3		18	1
50	2024-12-12 10:24:30.624805+05	246	a	3		18	1
51	2024-12-12 10:24:30.625907+05	245	q	3		18	1
52	2024-12-12 10:24:30.626914+05	244	t	3		18	1
53	2024-12-12 10:24:30.627952+05	243	z	3		18	1
54	2024-12-12 10:24:30.629249+05	242	s	3		18	1
55	2024-12-12 10:24:30.630637+05	241	f	3		18	1
56	2024-12-12 10:24:30.631388+05	240	t	3		18	1
57	2024-12-12 10:24:30.632329+05	239	r	3		18	1
58	2024-12-12 10:24:30.633236+05	238	t	3		18	1
59	2024-12-12 10:24:30.634207+05	237	t	3		18	1
60	2024-12-12 10:24:30.63517+05	236	q	3		18	1
61	2024-12-12 10:24:30.636172+05	235	t	3		18	1
62	2024-12-12 10:24:30.637228+05	234	z	3		18	1
63	2024-12-12 10:24:30.638315+05	233	h	3		18	1
64	2024-12-12 10:24:30.639347+05	232	a	3		18	1
65	2024-12-12 10:24:30.640315+05	231	xaxa	3		18	1
66	2024-12-12 10:24:30.641236+05	230	qale	3		18	1
67	2024-12-12 10:24:30.642163+05	229	qale	3		18	1
68	2024-12-12 10:24:30.643257+05	228	g	3		18	1
69	2024-12-12 10:24:30.644472+05	227	q	3		18	1
70	2024-12-12 10:24:30.645636+05	226	df	3		18	1
71	2024-12-12 10:24:30.647025+05	225	asd	3		18	1
72	2024-12-12 10:24:30.64811+05	224	g	3		18	1
73	2024-12-12 10:24:30.648978+05	223	qale	3		18	1
74	2024-12-12 10:24:30.649894+05	222	2	3		18	1
75	2024-12-12 10:24:30.650792+05	221	2	3		18	1
76	2024-12-12 10:24:30.6518+05	220	188	3		18	1
77	2024-12-12 10:24:30.652721+05	219	188	3		18	1
78	2024-12-12 10:24:30.65369+05	218	188	3		18	1
79	2024-12-12 10:24:30.654668+05	217	tg://user?id=7162720	3		18	1
80	2024-12-12 10:24:30.655542+05	216	188	3		18	1
81	2024-12-12 10:24:30.656411+05	215	public qildingmi?	3		18	1
82	2024-12-12 10:24:30.657358+05	214	188	3		18	1
83	2024-12-12 10:24:30.658324+05	213	#rasm\n\npanis 202%\nQP	3		18	1
84	2024-12-12 10:24:30.659215+05	212	панис 202%\nҚП\n\n8-ауг	3		18	1
85	2024-12-12 10:24:30.660352+05	211	манабундай\n\nва \n\nана	3		18	1
86	2024-12-12 10:24:30.661111+05	210	#rasm\n\naSDKAS KSDJK 	3		18	1
87	2024-12-12 10:24:30.662296+05	209	#rasm\n\nmanabunday\n\nv	3		18	1
88	2024-12-12 10:24:30.663769+05	208	#rasm\n\nsecond bot\nbo	3		18	1
89	2024-12-12 10:24:30.664767+05	207	#rasm\n\nbormisize	3		18	1
90	2024-12-12 10:24:30.665649+05	206	#video\n\nbratanim	3		18	1
91	2024-12-12 10:24:30.666707+05	205	c	3		18	1
92	2024-12-12 10:24:30.667714+05	204	mac alister	3		18	1
93	2024-12-12 10:24:30.668699+05	203	secund	3		18	1
94	2024-12-12 10:24:30.669677+05	202	second	3		18	1
95	2024-12-12 10:24:30.670608+05	201	#rasm\n\nsecond bot\nbo	3		18	1
96	2024-12-12 10:24:30.671475+05	200	#rasm\n\npanis 202%\nQP	3		18	1
97	2024-12-12 10:24:30.672303+05	199	#rasm\n\n	3		18	1
98	2024-12-12 10:24:30.673158+05	198	#rasm\n\n	3		18	1
99	2024-12-12 10:24:30.673926+05	197	#rasm\n\nЎғилшод	3		18	1
100	2024-12-12 10:24:30.674789+05	196	#rasm\n\nO'g'ilshod	3		18	1
101	2024-12-12 10:24:30.675307+05	195	#rasm\n\nzorkua	3		18	1
102	2024-12-12 10:24:30.676032+05	194	қалесиз братаним	3		18	1
103	2024-12-12 10:24:30.676782+05	193	qalesiz bratanim	3		18	1
104	2024-12-12 10:24:30.677557+05	192	зормисиз	3		18	1
105	2024-12-12 10:24:30.678589+05	191	qalesiz	3		18	1
106	2024-12-12 10:24:30.682408+05	190	qale	3		18	1
107	2024-12-12 10:24:30.683549+05	189	#rasm\n\npanis 202%\nQP	3		18	1
108	2024-12-12 10:24:30.684569+05	188	гостиница	3		18	1
109	2024-12-12 10:24:30.685546+05	187	крыса	3		18	1
110	2024-12-12 10:24:37.967746+05	186	#rasm\n\nменынг	3		18	1
111	2024-12-12 10:24:37.970274+05	185	#rasm\n\nфывф фыв фывф	3		18	1
112	2024-12-12 10:24:37.971644+05	184	#rasm\n\nqalesiz	3		18	1
113	2024-12-12 10:24:37.974073+05	183	qael	3		18	1
114	2024-12-12 10:24:37.975519+05	182	#rasm\n\npanis 202%\nQP	3		18	1
115	2024-12-12 10:24:37.976707+05	181	#rasm\n\npanis 202%\nQP	3		18	1
116	2024-12-12 10:24:37.977762+05	180	ўғилшид	3		18	1
117	2024-12-12 10:24:37.978717+05	179	o'g'ilshid	3		18	1
118	2024-12-12 10:24:37.979411+05	178	салом	3		18	1
119	2024-12-12 10:24:37.980285+05	177	salom	3		18	1
120	2024-12-12 10:24:37.981143+05	176	o'g'	3		18	1
121	2024-12-12 10:24:37.981954+05	175	qale	3		18	1
122	2024-12-12 10:24:37.982824+05	174	qoyile	3		18	1
123	2024-12-12 10:24:37.983769+05	173	zorkua	3		18	1
124	2024-12-12 10:24:37.984599+05	172	chota qotvottimi	3		18	1
125	2024-12-12 10:24:37.985405+05	171	g	3		18	1
126	2024-12-12 10:24:37.986438+05	170	f	3		18	1
127	2024-12-12 10:24:37.987574+05	169	xaxa	3		18	1
128	2024-12-12 10:24:37.988905+05	168	#video\n\nqag'aroq O'g	3		18	1
129	2024-12-12 10:24:37.99156+05	167	gap yoge	3		18	1
130	2024-12-12 10:24:37.992718+05	166	xaxa	3		18	1
131	2024-12-12 10:24:37.993704+05	165	g`urur bormi?	3		18	1
132	2024-12-12 10:24:37.994603+05	164	o`zimdan o`rgilay 😁	3		18	1
133	2024-12-12 10:24:37.99518+05	163	o'zimdan o'rgilay 😁	3		18	1
134	2024-12-12 10:24:37.995909+05	162	kimdir Oʻgʻilshodni 	3		18	1
135	2024-12-12 10:24:37.996644+05	161	кимдир Ўғилшодни сев	3		18	1
136	2024-12-12 10:24:37.997591+05	160	#rasm\n\nкимдир Ўғилшо	3		18	1
137	2024-12-12 10:24:37.998709+05	159	кимдир Ўғилшодни сев	3		18	1
138	2024-12-12 10:24:38.000122+05	158	кимдир Ўғилшодни сев	3		18	1
139	2024-12-12 10:24:38.001415+05	157	кимдир Ўғилшодни сев	3		18	1
140	2024-12-12 10:24:38.002902+05	156	улп	3		18	1
141	2024-12-12 10:24:38.004654+05	155	вапв	3		18	1
142	2024-12-12 10:24:38.007136+05	154	фывф	3		18	1
143	2024-12-12 10:24:38.009336+05	153	кимдир Ўғилшодни сев	3		18	1
144	2024-12-12 10:24:38.010515+05	152	#rasm\n\nkimdir O'g'il	3		18	1
145	2024-12-12 10:24:38.011673+05	151	O’g’ilshod	3		18	1
146	2024-12-12 10:24:38.01289+05	150	o'g'ilshod	3		18	1
147	2024-12-12 10:24:38.014039+05	149	kimdir O'g'ilshodni 	3		18	1
148	2024-12-12 10:24:38.014886+05	148	tsimikas	3		18	1
149	2024-12-12 10:24:38.015998+05	147	tsimikas	3		18	1
150	2024-12-12 10:24:38.017074+05	146	kimdir O'g'ilshodni 	3		18	1
151	2024-12-12 10:24:38.018084+05	145	O’g’ilshod	3		18	1
152	2024-12-12 10:24:38.019138+05	144	O’g’ilshod	3		18	1
153	2024-12-12 10:24:38.021009+05	143	O‘	3		18	1
154	2024-12-12 10:24:38.02244+05	142	O’	3		18	1
155	2024-12-12 10:24:38.02509+05	141	O’g’ilshod	3		18	1
156	2024-12-12 10:24:38.026457+05	140	O'g'ilshod	3		18	1
157	2024-12-12 10:24:38.02737+05	139	o'rdak	3		18	1
158	2024-12-12 10:24:38.028228+05	138	g'oz	3		18	1
159	2024-12-12 10:24:38.029235+05	137	tovuq	3		18	1
160	2024-12-12 10:24:38.030251+05	136	o‘rdak	3		18	1
161	2024-12-12 10:24:38.031204+05	135	o`rdak	3		18	1
162	2024-12-12 10:24:38.032298+05	134	o'rdak	3		18	1
163	2024-12-12 10:24:38.033151+05	133	o‘rdak	3		18	1
164	2024-12-12 10:24:38.034074+05	132	[🚫]\n\no‘rdak	3		18	1
165	2024-12-12 10:24:38.034896+05	131	o'rdak	3		18	1
166	2024-12-12 10:24:38.035673+05	130	[🚫]\n\n‘	3		18	1
167	2024-12-12 10:24:38.036961+05	129	ko'krak	3		18	1
168	2024-12-12 10:24:38.03802+05	128	o'rdak	3		18	1
169	2024-12-12 10:24:38.039765+05	127	o'	3		18	1
170	2024-12-12 10:24:38.040954+05	126	o`	3		18	1
171	2024-12-12 10:24:38.041984+05	125	o'	3		18	1
172	2024-12-12 10:24:38.042902+05	124	[🚫]\n\no‘	3		18	1
173	2024-12-12 10:24:38.043906+05	123	s	3		18	1
174	2024-12-12 10:24:38.044926+05	122	[🚫]\n\no‘	3		18	1
175	2024-12-12 10:24:38.045947+05	121	[🚫]\n\no‘	3		18	1
176	2024-12-12 10:24:38.046973+05	120	[🚫]\n\no‘	3		18	1
177	2024-12-12 10:24:38.048225+05	119	[🚫]\n\no‘	3		18	1
178	2024-12-12 10:24:38.04912+05	118	yo	3		18	1
179	2024-12-12 10:24:38.050317+05	117	CH	3		18	1
180	2024-12-12 10:24:38.05145+05	116	ch	3		18	1
181	2024-12-12 10:24:38.052435+05	115	yahmat	3		18	1
182	2024-12-12 10:24:38.053442+05	114	yordam	3		18	1
183	2024-12-12 10:24:38.05736+05	113	o'rdak	3		18	1
184	2024-12-12 10:24:38.058793+05	112	daxshat	3		18	1
185	2024-12-12 10:24:38.0601+05	111	mening o'g'limning i	3		18	1
186	2024-12-12 10:24:38.061347+05	110	o'sha	3		18	1
187	2024-12-12 10:24:38.062473+05	109	ahmoq	3		18	1
188	2024-12-12 10:24:38.064254+05	108	garang	3		18	1
189	2024-12-12 10:24:38.065802+05	107	ahmoq	3		18	1
190	2024-12-12 10:24:38.066933+05	106	g'	3		18	1
191	2024-12-12 10:24:38.068058+05	105	o'	3		18	1
192	2024-12-12 10:24:38.069053+05	104	g	3		18	1
193	2024-12-12 10:24:38.070159+05	103	f	3		18	1
194	2024-12-12 10:24:38.071204+05	102	s	3		18	1
195	2024-12-12 10:24:38.072483+05	101	s	3		18	1
196	2024-12-12 10:24:38.074039+05	100	s	3		18	1
197	2024-12-12 10:24:38.075128+05	99	o'g'lim	3		18	1
198	2024-12-12 10:24:38.076299+05	98	o'g'lim	3		18	1
199	2024-12-12 10:24:38.077399+05	97	[🚫]\n\n‘	3		18	1
200	2024-12-12 10:24:38.078395+05	96	[🚫]\n\nʻ	3		18	1
201	2024-12-12 10:24:38.079439+05	95	[🚫]\n\n‘	3		18	1
202	2024-12-12 10:24:38.080455+05	94	o	3		18	1
203	2024-12-12 10:24:38.081402+05	93	g	3		18	1
204	2024-12-12 10:24:38.082554+05	92	h	3		18	1
205	2024-12-12 10:24:38.083726+05	91	s	3		18	1
206	2024-12-12 10:24:38.084824+05	90	sh	3		18	1
207	2024-12-12 10:24:38.085822+05	89	o'	3		18	1
208	2024-12-12 10:24:38.087055+05	88	[🚫]\n\no‘	3		18	1
209	2024-12-12 10:24:38.088304+05	87	[🚫]\n\ng‘	3		18	1
210	2024-12-12 10:24:43.338379+05	86	[🚫]\n\nOʻ	3		18	1
211	2024-12-12 10:24:43.3405+05	85	[🚫]\n\noʻ	3		18	1
212	2024-12-12 10:24:43.341759+05	84	o'rdak	3		18	1
213	2024-12-12 10:24:43.34289+05	83	yalla	3		18	1
214	2024-12-12 10:24:43.344504+05	82	yalla	3		18	1
215	2024-12-12 10:24:43.3464+05	81	ғалла	3		18	1
216	2024-12-12 10:24:43.347603+05	80	o'rdak	3		18	1
217	2024-12-12 10:24:43.349068+05	79	o'rdak	3		18	1
218	2024-12-12 10:24:43.350311+05	78	yo'	3		18	1
219	2024-12-12 10:24:43.352318+05	77	O'	3		18	1
220	2024-12-12 10:24:43.353743+05	76	o'	3		18	1
221	2024-12-12 10:24:43.355776+05	75	ch	3		18	1
222	2024-12-12 10:24:43.35697+05	74	g	3		18	1
223	2024-12-12 10:24:43.357737+05	73	f	3		18	1
224	2024-12-12 10:24:43.358815+05	72	s	3		18	1
225	2024-12-12 10:24:43.359803+05	71	mening o'g'limning i	3		18	1
226	2024-12-12 10:24:43.360784+05	70	#rasm\n\n	3		18	1
227	2024-12-12 10:24:43.362479+05	69	#rasm\n\naha	3		18	1
228	2024-12-12 10:24:43.366466+05	68	zormi	3		18	1
229	2024-12-12 10:24:43.368754+05	67	s	3		18	1
230	2024-12-12 10:24:43.370559+05	66	z	3		18	1
231	2024-12-12 10:24:43.372448+05	65	#rasm\n\nXatolik yuz b	3		18	1
232	2024-12-12 10:24:43.379113+05	64	#rasm\n\nzore	3		18	1
233	2024-12-12 10:24:43.380801+05	63	asd	3		18	1
234	2024-12-12 10:24:43.383307+05	62	#rasm\n\nMatnni o'qib 	3		18	1
235	2024-12-12 10:24:43.38641+05	61	#rasm\n\nzora	3		18	1
236	2024-12-12 10:24:43.391428+05	60	qa	3		18	1
237	2024-12-12 10:24:43.395838+05	59	#rasm\n\nMatnni o'qib 	3		18	1
238	2024-12-12 10:24:43.397397+05	58	#rasm\n\nnimaa	3		18	1
239	2024-12-12 10:24:43.399069+05	57	#rasm\n\nMatnni o'qib 	3		18	1
240	2024-12-12 10:24:43.400432+05	56	#rasm\n\nbore	3		18	1
241	2024-12-12 10:24:43.402864+05	55	zorkua	3		18	1
242	2024-12-12 10:24:43.404555+05	54	#rasm\n\n	3		18	1
243	2024-12-12 10:24:43.406293+05	53	#rasm\n\n	3		18	1
244	2024-12-12 10:24:43.407816+05	52	#rasm\n\n	3		18	1
245	2024-12-12 10:24:43.409793+05	51	#rasm\n\n	3		18	1
246	2024-12-12 10:24:43.411839+05	50	#rasm\n\nqani	3		18	1
247	2024-12-12 10:24:43.412939+05	49	zorda	3		18	1
248	2024-12-12 10:24:43.414326+05	48	#rasm\n\n	3		18	1
249	2024-12-12 10:24:43.416878+05	47	#rasm\n\nbarakalla	3		18	1
250	2024-12-12 10:24:43.4191+05	46	endichi	3		18	1
251	2024-12-12 10:24:43.421846+05	45	#rasm\n\n	3		18	1
252	2024-12-12 10:24:43.424191+05	44	xaxa	3		18	1
253	2024-12-12 10:24:43.426024+05	43	#rasm\n\nchumadm	3		18	1
254	2024-12-12 10:24:43.430264+05	42	#rasm\n\n	3		18	1
255	2024-12-12 10:24:43.433034+05	41	#rasm\n\n	3		18	1
256	2024-12-12 10:24:43.435362+05	40	#rasm\n\nzorkua	3		18	1
257	2024-12-12 10:24:43.436833+05	39	qale	3		18	1
258	2024-12-12 10:24:43.438352+05	38	#rasm\n\nendichi	3		18	1
259	2024-12-12 10:24:43.439728+05	37	xa	3		18	1
260	2024-12-12 10:24:43.441056+05	36	chundin	3		18	1
261	2024-12-12 10:24:43.442237+05	35	asd	3		18	1
262	2024-12-12 10:24:43.443304+05	34	a	3		18	1
263	2024-12-12 10:24:43.444175+05	33	qale	3		18	1
264	2024-12-12 10:24:43.445057+05	32	ad	3		18	1
265	2024-12-12 10:24:43.446057+05	31	qale	3		18	1
266	2024-12-12 10:24:43.446997+05	30	ds	3		18	1
267	2024-12-12 10:24:43.447955+05	29	asd	3		18	1
268	2024-12-12 10:24:43.448571+05	28	3	3		18	1
269	2024-12-12 10:24:43.44952+05	27	da	3		18	1
270	2024-12-12 10:24:43.450553+05	26	t	3		18	1
271	2024-12-12 10:24:43.452312+05	25	f	3		18	1
272	2024-12-12 10:24:43.453515+05	24	s	3		18	1
273	2024-12-12 10:24:43.457374+05	23	/bot 2 52 ttt	3		18	1
274	2024-12-12 10:24:43.458353+05	22	f	3		18	1
275	2024-12-12 10:24:43.45932+05	21	s	3		18	1
276	2024-12-12 10:24:43.460318+05	20	qale	3		18	1
277	2024-12-12 10:24:43.461525+05	19	akmoq	3		18	1
278	2024-12-12 10:24:43.462619+05	18	2	3		18	1
279	2024-12-12 10:24:43.463721+05	17	s	3		18	1
280	2024-12-12 10:24:43.465069+05	16	s	3		18	1
281	2024-12-12 10:24:43.466274+05	15	qa	3		18	1
282	2024-12-12 10:24:43.468751+05	14	z	3		18	1
283	2024-12-12 10:24:43.469568+05	13	s	3		18	1
284	2024-12-12 10:24:43.470565+05	12	t	3		18	1
285	2024-12-12 10:24:43.47152+05	11	l	3		18	1
286	2024-12-12 10:24:43.472524+05	10	t	3		18	1
287	2024-12-12 10:24:43.473622+05	9	f	3		18	1
288	2024-12-12 10:24:43.474537+05	8	g	3		18	1
289	2024-12-12 10:24:43.475518+05	7	q	3		18	1
290	2024-12-12 10:24:43.476612+05	6	g	3		18	1
291	2024-12-12 10:24:43.477702+05	5	g	3		18	1
292	2024-12-12 10:24:43.478662+05	4	a	3		18	1
293	2024-12-12 10:24:43.479593+05	3	/users	3		18	1
294	2024-12-12 10:24:43.480542+05	2	/users	3		18	1
295	2024-12-12 10:24:43.481899+05	1	/users	3		18	1
296	2024-12-12 10:41:36.18231+05	290	tovuq miyya	3		18	1
297	2024-12-12 10:41:36.183622+05	289	ratatata	3		18	1
298	2024-12-12 10:41:36.184334+05	288	a	3		18	1
299	2024-12-12 10:41:36.185006+05	287	a	3		18	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	django_celery_beat	crontabschedule
8	django_celery_beat	intervalschedule
9	django_celery_beat	periodictask
10	django_celery_beat	periodictasks
11	django_celery_beat	solarschedule
12	django_celery_beat	clockedschedule
13	common	code
14	common	language
15	common	requiredchannels
16	common	telegramprofile
17	common	banneduser
18	common	archive
19	common	text
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-12-08 00:16:34.95852+05
2	auth	0001_initial	2024-12-08 00:16:35.000946+05
3	admin	0001_initial	2024-12-08 00:16:35.01359+05
4	admin	0002_logentry_remove_auto_add	2024-12-08 00:16:35.019784+05
5	admin	0003_logentry_add_action_flag_choices	2024-12-08 00:16:35.025204+05
6	contenttypes	0002_remove_content_type_name	2024-12-08 00:16:35.033475+05
7	auth	0002_alter_permission_name_max_length	2024-12-08 00:16:35.038451+05
8	auth	0003_alter_user_email_max_length	2024-12-08 00:16:35.043267+05
9	auth	0004_alter_user_username_opts	2024-12-08 00:16:35.047081+05
10	auth	0005_alter_user_last_login_null	2024-12-08 00:16:35.051343+05
11	auth	0006_require_contenttypes_0002	2024-12-08 00:16:35.052124+05
12	auth	0007_alter_validators_add_error_messages	2024-12-08 00:16:35.056084+05
13	auth	0008_alter_user_username_max_length	2024-12-08 00:16:35.064096+05
14	auth	0009_alter_user_last_name_max_length	2024-12-08 00:16:35.070747+05
15	auth	0010_alter_group_name_max_length	2024-12-08 00:16:35.07646+05
16	auth	0011_update_proxy_permissions	2024-12-08 00:16:35.080934+05
17	auth	0012_alter_user_first_name_max_length	2024-12-08 00:16:35.085614+05
18	common	0001_initial	2024-12-08 00:16:35.144189+05
19	django_celery_beat	0001_initial	2024-12-08 00:16:35.172828+05
20	django_celery_beat	0002_auto_20161118_0346	2024-12-08 00:16:35.189803+05
21	django_celery_beat	0003_auto_20161209_0049	2024-12-08 00:16:35.198897+05
22	django_celery_beat	0004_auto_20170221_0000	2024-12-08 00:16:35.20194+05
23	django_celery_beat	0005_add_solarschedule_events_choices	2024-12-08 00:16:35.204739+05
24	django_celery_beat	0006_auto_20180322_0932	2024-12-08 00:16:35.228357+05
25	django_celery_beat	0007_auto_20180521_0826	2024-12-08 00:16:35.240086+05
26	django_celery_beat	0008_auto_20180914_1922	2024-12-08 00:16:35.261637+05
27	django_celery_beat	0006_auto_20180210_1226	2024-12-08 00:16:35.299034+05
28	django_celery_beat	0006_periodictask_priority	2024-12-08 00:16:35.306018+05
29	django_celery_beat	0009_periodictask_headers	2024-12-08 00:16:35.312309+05
30	django_celery_beat	0010_auto_20190429_0326	2024-12-08 00:16:35.42849+05
31	django_celery_beat	0011_auto_20190508_0153	2024-12-08 00:16:35.440503+05
32	django_celery_beat	0012_periodictask_expire_seconds	2024-12-08 00:16:35.447054+05
33	django_celery_beat	0013_auto_20200609_0727	2024-12-08 00:16:35.453715+05
34	django_celery_beat	0014_remove_clockedschedule_enabled	2024-12-08 00:16:35.45646+05
35	django_celery_beat	0015_edit_solarschedule_events_choices	2024-12-08 00:16:35.458904+05
36	django_celery_beat	0016_alter_crontabschedule_timezone	2024-12-08 00:16:35.466571+05
37	django_celery_beat	0017_alter_crontabschedule_month_of_year	2024-12-08 00:16:35.473548+05
38	django_celery_beat	0018_improve_crontab_helptext	2024-12-08 00:16:35.479143+05
39	django_celery_beat	0019_alter_periodictasks_options	2024-12-08 00:16:35.481922+05
40	sessions	0001_initial	2024-12-08 00:16:35.490675+05
41	common	0002_requiredchannels_chat_id	2024-12-11 00:32:23.58146+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
setqp1mzg1i8q2pclvo76rvqw1c0cg29	.eJxVjDsOwjAQBe_iGln-yR9Kes5g7a7XOIAcKU4qxN0hUgpo38y8l8iwrS1vg5c8FXEWWpx-NwR6cN9BuUO_zZLmvi4Tyl2RBx3yOhd-Xg7376DBaN_aaHSKtQ8W2CtblXGVoXKM5Bh9SDEmxJAC2GRsQfBJk_KOiqHoNYr3B94cN9k:1tK0Ic:LluQyNDlT2u3KXxSPvFn9NaNsscHNkXz6I0tznzSnuc	2024-12-22 00:17:06.048185+05
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: common_archive_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_archive_id_seq', 290, true);


--
-- Name: common_banneduser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_banneduser_id_seq', 16, true);


--
-- Name: common_code_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_code_id_seq', 1, false);


--
-- Name: common_language_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_language_id_seq', 1, false);


--
-- Name: common_requiredchannels_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_requiredchannels_id_seq', 2, true);


--
-- Name: common_telegramprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_telegramprofile_id_seq', 247, true);


--
-- Name: common_text_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.common_text_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 299, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: common_archive common_archive_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_archive
    ADD CONSTRAINT common_archive_pkey PRIMARY KEY (id);


--
-- Name: common_banneduser common_banneduser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_banneduser
    ADD CONSTRAINT common_banneduser_pkey PRIMARY KEY (id);


--
-- Name: common_code common_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_code
    ADD CONSTRAINT common_code_pkey PRIMARY KEY (id);


--
-- Name: common_code common_code_title_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_code
    ADD CONSTRAINT common_code_title_key UNIQUE (title);


--
-- Name: common_language common_language_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_language
    ADD CONSTRAINT common_language_code_key UNIQUE (code);


--
-- Name: common_language common_language_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_language
    ADD CONSTRAINT common_language_pkey PRIMARY KEY (id);


--
-- Name: common_requiredchannels common_requiredchannels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_requiredchannels
    ADD CONSTRAINT common_requiredchannels_pkey PRIMARY KEY (id);


--
-- Name: common_requiredchannels common_requiredchannels_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_requiredchannels
    ADD CONSTRAINT common_requiredchannels_url_key UNIQUE (url);


--
-- Name: common_telegramprofile common_telegramprofile_chat_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_telegramprofile
    ADD CONSTRAINT common_telegramprofile_chat_id_key UNIQUE (chat_id);


--
-- Name: common_telegramprofile common_telegramprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_telegramprofile
    ADD CONSTRAINT common_telegramprofile_pkey PRIMARY KEY (id);


--
-- Name: common_telegramprofile common_telegramprofile_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_telegramprofile
    ADD CONSTRAINT common_telegramprofile_username_key UNIQUE (username);


--
-- Name: common_text common_text_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_text
    ADD CONSTRAINT common_text_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: common_archive_author_id_19909276; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_archive_author_id_19909276 ON public.common_archive USING btree (author_id);


--
-- Name: common_banneduser_telegram_profile_id_b21099d6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_banneduser_telegram_profile_id_b21099d6 ON public.common_banneduser USING btree (telegram_profile_id);


--
-- Name: common_code_title_b2cfd3c5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_code_title_b2cfd3c5_like ON public.common_code USING btree (title varchar_pattern_ops);


--
-- Name: common_language_code_9246e838_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_language_code_9246e838_like ON public.common_language USING btree (code varchar_pattern_ops);


--
-- Name: common_requiredchannels_url_e73032a3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_requiredchannels_url_e73032a3_like ON public.common_requiredchannels USING btree (url varchar_pattern_ops);


--
-- Name: common_telegramprofile_chat_id_97a3e993_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_telegramprofile_chat_id_97a3e993_like ON public.common_telegramprofile USING btree (chat_id varchar_pattern_ops);


--
-- Name: common_telegramprofile_username_4b8ab319_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_telegramprofile_username_4b8ab319_like ON public.common_telegramprofile USING btree (username varchar_pattern_ops);


--
-- Name: common_text_code_id_73b29d32; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_text_code_id_73b29d32 ON public.common_text USING btree (code_id);


--
-- Name: common_text_language_id_2faf5ed5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX common_text_language_id_2faf5ed5 ON public.common_text USING btree (language_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: common_archive common_archive_author_id_19909276_fk_common_telegramprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_archive
    ADD CONSTRAINT common_archive_author_id_19909276_fk_common_telegramprofile_id FOREIGN KEY (author_id) REFERENCES public.common_telegramprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: common_banneduser common_banneduser_telegram_profile_id_b21099d6_fk_common_te; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_banneduser
    ADD CONSTRAINT common_banneduser_telegram_profile_id_b21099d6_fk_common_te FOREIGN KEY (telegram_profile_id) REFERENCES public.common_telegramprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: common_text common_text_code_id_73b29d32_fk_common_code_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_text
    ADD CONSTRAINT common_text_code_id_73b29d32_fk_common_code_id FOREIGN KEY (code_id) REFERENCES public.common_code(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: common_text common_text_language_id_2faf5ed5_fk_common_language_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.common_text
    ADD CONSTRAINT common_text_language_id_2faf5ed5_fk_common_language_id FOREIGN KEY (language_id) REFERENCES public.common_language(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

