# Generated by Django 5.0.6 on 2024-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredchannels',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
