# Generated by Django 5.0.6 on 2024-12-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_archive_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='title',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='file_id',
            new_name='type',
        ),
    ]
