# Generated by Django 5.0.6 on 2024-12-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_type_archive_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='title',
            new_name='type',
        ),
    ]
